<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRVY10To\Pimcore_Bundle_InstallBundle_InstallerKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRVY10To/Pimcore_Bundle_InstallBundle_InstallerKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRVY10To.legacy');

    return;
}

if (!\class_exists(Pimcore_Bundle_InstallBundle_InstallerKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRVY10To\Pimcore_Bundle_InstallBundle_InstallerKernelDevDebugContainer::class, Pimcore_Bundle_InstallBundle_InstallerKernelDevDebugContainer::class, false);
}

return new \ContainerRVY10To\Pimcore_Bundle_InstallBundle_InstallerKernelDevDebugContainer([
    'container.build_hash' => 'RVY10To',
    'container.build_id' => '3813eea3',
    'container.build_time' => 1674811476,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRVY10To');
