<?php

namespace ContainerGjMAT7G;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JzheGmeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jzheGme' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jzheGme'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'context' => ['privates', '.errored..service_locator.jzheGme.Pimcore\\Model\\DataObject\\Data\\CalculatedValue', NULL, 'Cannot autowire service ".service_locator.jzheGme": it references class "Pimcore\\Model\\DataObject\\Data\\CalculatedValue" but no such service exists.'],
            'object' => ['privates', '.errored..service_locator.jzheGme.Pimcore\\Model\\DataObject\\Concrete', NULL, 'Cannot autowire service ".service_locator.jzheGme": it references class "Pimcore\\Model\\DataObject\\Concrete" but no such service exists.'],
        ], [
            'context' => 'Pimcore\\Model\\DataObject\\Data\\CalculatedValue',
            'object' => 'Pimcore\\Model\\DataObject\\Concrete',
        ]);
    }
}
