<?php

namespace ContainerGjMAT7G;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalculatedValueService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.jzheGme.Pimcore\Model\DataObject\Data\CalculatedValue' shared service.
     *
     * @return \Pimcore\Model\DataObject\Data\CalculatedValue
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.jzheGme": it references class "Pimcore\\Model\\DataObject\\Data\\CalculatedValue" but no such service exists.');
    }
}
