<?php

namespace ContainerGjMAT7G;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalculatorControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CalculatorController' shared autowired service.
     *
     * @return \App\Controller\CalculatorController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/CalculatorClassInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/CalculatorController.php';

        return $container->services['App\\Controller\\CalculatorController'] = new \App\Controller\CalculatorController();
    }
}
