<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIToDAEu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIToDAEu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIToDAEu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIToDAEu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIToDAEu\App_KernelDevDebugContainer([
    'container.build_hash' => 'IToDAEu',
    'container.build_id' => '37657d60',
    'container.build_time' => 1675924469,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIToDAEu');
